nix-community/nixos-anywhere

- README.md
- nixos-remote
initial version of nixos-remote. takes a flake like https://github.com/Lassulus/flakes-testing to format/install
> init nixos-remote

- nixos-remote
This changes our rsync invocation so that the remote copies of --extra-files always belong to `root:root`. I believe that's a safer default than copying local permissions in all cases. Without this change, files which should belong to root would need to locally belong to root as well. In cases where one would like other permissions on the remote system, one could chown them after copying.
> Don't preserve local permissions for --extra-files

- nixos-remote
- tests/from-nixos-with-sudo.nix
- tests/from-nixos.nix
Similar to `--extra-files`, but files are copied before partitioning and installation. This allows to specify i.e. disk encryption keys.
> Add --disk-encryption-keys option

- README.md
Without this change users will be running the script directly and might encounter errors as they are using the script unpackaged without its dependencies.
> README: suggest the use of the packaged script

- .github/settings.yml
This stops bors from merging things... we need a better strategy here (maybe a check that only runs in staging?)
> undo require bors as required check

- src/nixos-remote.sh
- For the sake of consistency I've renamed the function `nixCopy` to `nix_copy`.
- Again, for for consistency I made `nix copy` and `nix build` have the same experimental features enabled.
- For `nix_build` it will no longer keep/create a `result` symlink in the current directory. Essentially our use for `nix build` is like the old CLI's `nix-store --realise`.
- Added the flag -L/--print-build-logs which passes this same flag to all invocations of `nix` via the `nix_options` bash array. This flag is also enabled by default when using the `--debug` flag.
> nixos-remote.sh: don't create symlink in dir & add --print-build-logs/-L flag

- src/nixos-remote.sh
After removing -a in #15, remote extra files are implictly chowned according to the remote umask. So we (re-)add --perms to apply local file permissions remotely as this should mostly be expected behavior.
The second -F disables uploading the .rsync-filter file itself if it exists.
> extra-files: use rsync -p, -FF

- src/nixos-remote.sh
I think that's a good default as downloading from cache.nixos.org is often at least as fast as uploading from the machine where nixos-remote runs and often much faster if running nixos-remote over a typical residential internet connection.
On my home network connection this reduces the whole time it takes to deploy a new hcloud machine from my workstation from ~11min to ~3min.
> run nix copy --substitute-on-destination by default

- src/nixos-remote.sh
This will get rid of pseudo tty warnings.
> disable pseudo tty allocation in ssh

- README.md
- src/nixos-remote.sh
This is useful if your binary cache already has pre-build the machine.
> add --from option

- src/nixos-anywhere.sh
cherry-picked from https://github.com/numtide/nixos-anywhere/pull/50
> nixos-remote: use installed ssh key also for rsync

- src/nixos-anywhere.sh
This is useful for automation i.e. our terraform module tries to run nixos-rebuild against the nixos installer instead of the actual machine.
> wait for machine to be shutdown after deploy

- src/nixos-anywhere.sh
In #88, I stumbled on this trying to install an OpenWRT target.
This is a band-aid for helpful errors and avoiding "half broken" states.
In an upcoming PR, I will suggest a solution which will produce static
binaries for what is needed and use them on the host.
> feat: detect bash & setsid presence and fail if they are not on the target

- README.md
- flake.nix
Use mdsh to keep the option parsing outputs in the README in sync with the script.
> README: format with mdsh

- README.md
- src/nixos-anywhere.sh
It's not strictly needed because Nix wraps it with writeShellApplication, but it makes it easier for the script to be standalone and use the right syntax highlighter in shells.
> src/nixos-anywhere.sh: add shebang

- docs/reference.md
- src/nixos-anywhere.sh
- tests/from-nixos-with-sudo.nix
- tests/from-nixos.nix
- tests/modules/installer.nix
Mirror the `-i` option from SSH, so you can run `nixos-anywhere ~/.ssh/other_key`.
This commit also fixes an issue where the generated key-pair would stay
around when using the SSH_PRIVATE_KEY env var.
> add -i to allow passing private key files

- README.md
As nixos-anywhere is a simple bash script, I'd expect it to run at least pretty much anywhere where nix, bash and curl are supported?
A user mentioned being confused about whether it would be supported to run nixos-anywhere *from* a macOS machine and I believe it should, but personally lack a machine to test it myself.
> Don't claim Linux requirement on source machine

- .gitignore
- src/nixos-anywhere.sh
Heya
I tried to run `nixos-anywhere` inside of a `nixpkgs/nix:latest` docker container (because I'd like to be able to use it on a system without nix installed locally).
Ran into the following infinite loop:
```bash
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/tmp/tmp.ebg98xQ7IX/nixos-anywhere.pub"
mktemp: failed to create directory via template '/root/.ssh/ssh-copy-id.XXXXXXXXXX': No such file or directory
/usr/bin/ssh-copy-id: ERROR: failed to create required temporary directory under ~/.ssh
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/tmp/tmp.ebg98xQ7IX/nixos-anywhere.pub"
mktemp: failed to create directory via template '/root/.ssh/ssh-copy-id.XXXXXXXXXX': No such file or directory
/usr/bin/ssh-copy-id: ERROR: failed to create required temporary …
```
> Create ~/.ssh folder and add .direnv to gitignore

- terraform/install/main.tf
- terraform/nixos-rebuild/deploy.sh
While running terraform with and without verbose mode enabled, we don't want the private key content to be shown in the terraform apply output.
> terraform: do not show private key in local-exec logs

- src/nixos-anywhere.sh
without this, the check gets run and fails even if no kexec will be done e.g. when an installer is booted
> move kexec check into kexec codepath

- src/default.nix
Pin nix to a version that has a working nix-copy-closure
See https://github.com/NixOS/nix/issues/8480
> fix blocking nix-copy-closure

- docs/quickstart.md
- src/nixos-anywhere.sh
depends on https://github.com/nix-community/disko/pull/299
> add --vm-test mode for local vm tests

- src/nixos-anywhere.sh
This is necessary for --post-kexec-ssh-port to be useful in situations involving port forwarding, such as when running on qemu
> Pass ssh_args to nix copy and nix build SSH invocations

- src/nixos-anywhere.sh
I use fish, but the current command will likely fail with nushell and others. Make the bash call explicit to avoid failures such as:
```
fish: Unsupported use of '='. In fish, please use 'set is_nixos $(if test -f /etc/os-release && grep -q ID=nixos /etc/os-release; then echo "y"; else echo "n"; fi)'.
```
Ideally this would be handled in `_ssh`, but there are some sporadic args for ssh in some of the calls. A quick perusal looked like they were just connection timeout options, which I'm wondering if we can move into `_ssh`. If this was done, then all calls could pass through bash. For now I've targeted the steps that require posix/bashisms.
> force use of bash to allow for non-posix user shells

- src/nixos-anywhere.sh
fixes args such as `--ssh-port` not affecting the whole program (specifically the keyscan porting was impacting my setup)
tests seem to pass ｏｋ
> use ssh args for getting connection settings

- docs/howtos/secrets.md
- docs/reference.md
- src/nixos-anywhere.sh
- tests/from-nixos.nix
nixos-kexec-installer preserves SSH host keys, so should we, to avoid changing host identity.
See also
- https://github.com/nix-community/nixos-images/blob/c4c73bce65306a1e747684dd0d4bcf0ab2779585/nix/kexec-installer/kexec-run.sh#L42C1-L46C1
- https://github.com/nix-community/nixos-images/blob/c4c73bce65306a1e747684dd0d4bcf0ab2779585/nix/installer.nix#L44-L55
> copy over ssh host keys

- docs/howtos/use-without-flakes.md
- docs/quickstart.md
trying to fix formatting issues and clarify it a bit, incorporating feedback by @chaoflow at oceansprint
> quickstart fixes

- docs/howtos/use-without-flakes.md
- src/nixos-anywhere.sh
potentially fixes https://github.com/nix-community/disko/issues/434
> umount /mnt prior to exporting zpool

- src/nixos-anywhere.sh
This is a bit faster and also helps to mitigated cases where additionally options that are not respected by ssh-keyscan (i.e. JumpHost) are used
> only fetch pubkey in case we want to build on remote

- src/default.nix
This sets up the package derivation to prefer the system rsync in the same way the system SSH is preferred, to prevent issues that may arise (e.g. crashes) that can arise from mixing the system SSH with the derivation-provided rsync.
Fixes #242.
> Prefer system rsync

- src/nixos-anywhere.sh
- terraform/install/main.tf
- terraform/install/run-nixos-anywhere.sh
- terraform/install/variables.tf
- tests/flake-module.nix
- tests/from-nixos-build-on-remote.nix
Remove the trusted user requirement for `--build-on-remote` by using `--store` instead of `--builders`
This is very useful for cross architecture deploys especially without any remote builders configured
> terraform/install: support `build_on_remote`

- src/nixos-anywhere.sh
In particular people might use openvz containers, which doesn't support kexec.
> detect containers

- docs/reference.md
- src/nixos-anywhere.sh
I haven't tested the manual version yet...
> [feat] remove -t parameter and replace it with a check of whether it's tty

- terraform/all-in-one.md
- terraform/all-in-one/main.tf
I need to access the store path while using `all-in-one` Terraform module but it's only exported from the `nix-build` TF module.
> feat(terraform): re-export store path result from all-in-one module

- src/nixos-anywhere.sh
When systemd-detect-virt exists and we aren't in a container, is_container contains `y none none` instead of `none`.
This causes nixos-anywhere to warn `WARNING: This script does not support running from a 'y' container. kexec will likely not work` even though we aren't in a container.
1. has outputs y/n to stdout which we need to remove
2. `systemd-detect-virt --container` returns non-zero when we aren't in a container, use if then else instead of && || to prevent duplicating `none` in is_container variable
Tested running against a stock debian 12 with bash as login shell
> Fix container detection

- src/nixos-anywhere.sh
Fix #279
Currently nixos-anywhere works with non-root users on non-NixOS installer/recovery images since it will kexec into a NixOS installer and proceed as root. But it doesn't work for NixOS installer if non-root user is used. Non-root user can be desirable if a preconfigured image is used both as Live CD and installer.
This PR allows non-root configuration by copying ~/.ssh/authorized_keys to /root/.ssh/authorized_keys and proceed as root (this should be fine regardless how user logs into the non-root user, since the nixos-anywhere.pub is what matters).
> Switch to root user if non-root user is used for nixos installer

- docs/quickstart.md
- src/default.nix
- src/nixos-anywhere.sh
Allow setting the bootstrap password on invocation of `nixos-anywhere`.
This makes use of the `sshpass` program, to provide `ssh-copy-id` with the password.
The `runtimeDeps` change in the following way:
sshpass: ∅ → 1.10, +29.5 KiB
Improves the usage especially together with the iso image installers of `nixos-images`.
> feat: add copy-password

- terraform/all-in-one/main.tf
- terraform/install/main.tf
- terraform/install/run-nixos-anywhere.sh
should fix issues with installing to ports other than the default
> Allow installs through terraform to work on different ports

- src/get-facts.sh
- src/nixos-anywhere.sh
This uses ip r g 1.1.1.1 to test if there's any route to an IPv4 internet host
If that fails and the url is a github.com one it will change github.com to gh-v6.com,
as specified in the documentation
This saves the user from an extra manual step and makes nixos-anywhere better
The fallback behaviour if the ip binary cannot be found is to just assume ipv4 connectivity. I can invert that if wanted.
> Detect IPv6 automatically, Rewrite kexec url

- src/get-facts.sh
It's a /bin/sh script, guys, it should be POSIX-compatible
> src/get-facts.sh: remove the bashism

- README.md
It seems that RAM requirements only apply when using kexec.
References (conflicting docs):
- https://github.com/nix-community/nixos-anywhere/blob/main/docs/requirements.md
- https://github.com/nix-community/nixos-anywhere/blob/main/docs/howtos/no-os.md
> fix(README): fix ram requirements without kexec

- flake.lock
- src/nixos-anywhere.sh
This allows to pass in special flags like "--no-sync" into the call to "kexec".
This does depend on a PR to `nixos-images`:
- https://github.com/nix-community/nixos-images/pull/228
> Add new parameter "--kexec-extra-flags"

- docs/howtos/use-without-flakes.md
- docs/quickstart.md
I had a hard time figuring out what to do, and all that's required is actually this.
most importantly, using the `noDeps` variant doesn't work because, obviously, it doesn't ship the dependencies
> docs: simplify non-flakes instructions

- src/nixos-anywhere.sh
Currently, `/mnt` will be unmounted and pools will be exported if `zpool` is in the `PATH`. However, that doesn't mean there are actually pools to export.
Partial fix for https://github.com/nix-community/nixos-anywhere/issues/278
> don't attempt to export zpool if there is none

- terraform/install/run-nixos-anywhere.sh
When used with `terranix`, if `SCRIPT_DIR` isn't fully resolved, Nix attempts to look for `flake.nix` in the wrong directory.
```
/nix/store/2djy58syb5jwyc0lbvmsradnimz77gqn-source
├── modules
│   ├── install -> /nix/store/3r4pxmns5pdcal30iwj0sg04iw8ghiqf-source/terraform/install
│   └── modules.json
├── plugin_path
└── providers
└── ...
```
```
module.install.null_resource.nixos-remote (local-exec): error: path '/nix/store/2djy58syb5jwyc0lbvmsradnimz77gqn-source/flake.nix' does not exist
╷
│ Error: local-exec provisioner error
│ 
│   with module.install.null_resource.nixos-remote,
│   on .terraform/modules/install/main.tf line 9, in resource "null_resource" "nixos-remote":
│    9:   provisioner "local-exec" {
│ 
│ Error running command '.terraform/modules/install/run-nixos-anywhere.sh ': …
```
> terraform/install: deal with symlinks better

- src/nixos-anywhere.sh
Hello!
I just used nixos-anywhere for the first time. It went fairly smoothly except for this surprise this at the end of my logs:
```
ssh: connect to host 192.168.1.146 port 22: Connection refused
```
It... "wait[ed] for the machine to become reachable again" only to stop immediately on a connection refused? Huh?
I looked through the nixos-anywhere source and it looks like this message is actually inverted -- we are waiting for the machine to become <i>un</i>reachable. I am deducing that from the fact that a previous step in the script that uses the same wait loop but says we are waiting for unreachability:
https://github.com/nix-community/nixos-anywhere/blob/f99d120b3788a286989db4e592a698f5d310d2f6/src/nixos-anywhere.sh#L417-L418
There also used to be a comment here that said …
> fix incorrect user explanation

- src/nixos-anywhere.sh
fixes https://github.com/nix-community/nixos-anywhere/issues/375
> Make ssh host optional again in vm-test

- src/nixos-anywhere.sh
- terraform/install/main.tf
- terraform/install/run-nixos-anywhere.sh
fixes https://github.com/nix-community/nixos-anywhere/pull/366
rebased version of the same
> Fixes relating to --build-on-remote

- src/nixos-anywhere.sh
Maybe there's a better way to do this, but it looks like removing elements from an array is kind of a pain.
> Re-invert behavior of --no-substitute-on-destination

- terraform/install/main.tf
This fixes the typos introduced by b699b3084dc8de18502ae0906eec67b4aaa7843c, which cause a Terraform semantic error.
> terraform: fix typos in phase subtraction

- docs/reference.md
- src/nixos-anywhere.sh
This means that users can now access the mounted filesystems by omitting the `reboot` phase.
You can combine this with `--disko-mode mount` to mount and upgrade an existing system before running `nixos-enter` to run commands on it.
$ nixos-anywhere --disko-mode mount --phases kexec,disko,install
@Mic92 I wonder if it would be worth adding a separate `unmount` phase
> nixos-anywhere: move unmount into `reboot` phase

- terraform/nix-build/nix-build.sh
currently, when `var.nix_options` is not set, the jq map action yields `null`, which ends up missing up. using a conditional here, we may instead account for this case such as to set it to empty string and avoid the issue.
> terraform/nix-build.sh: prevent error on empty nix_options

- src/nixos-anywhere.sh
Fixing the git add hardware config logic in case the user provides a relative path. We're doing two things:
1. Failing loudly if the git add command fails. At that point, we already know git is in $PATH. If the git add fails, the evaluation will likely fail in a flake setting. Better fail early with a helpful git error message.
2. We're resolving the hardware config path in the CLI parsing layer to make sure this path has the meaning the user intented it to have.
> hardware config: fix git add logic

- src/nixos-anywhere.sh
This is useful for users who use a similar `extendModules` pattern like `virtualisation.vmVariant`, where an extended NixOS configuration lives inside an existing configuration:
nixos-anywhere --flake .#nixosConfigurations.alpha.config.virtualisation.vmVariant
> nixos-anywhere: allow users to specify custom path NixOS configurations

- src/nixos-anywhere.sh
There seems to be no scenario where we aren't root on the target system at this point.
But there is one where it breaks: If hasSudo is true because the pre-kexec env had it, but kexec env does not.
Fixes #431
> Don't use sudo when uploading extraFiles

- docs/cli.md
- docs/howtos/disko-modes.md
- docs/howtos/no-os.md
- docs/howtos/secrets.md
- docs/quickstart.md
- src/nixos-anywhere.sh
Mirror the option from nixos-rebuild, so both have the same signature:
* Bootstrap: `nixos-anywhere --flake .#targethost --target-host root@1.2.3.4`
* Deploy: `nixos-rebuild --flake .#targethost --target-host root@1.2.3.4 switch`
> nixos-anywhere: add --target-host option

- docs/cli.md
- docs/howtos/INDEX.md
- docs/howtos/extra-files.md
- docs/reference.md
- src/nixos-anywhere.sh
Add a howto for `--extra-files`
#283
> docs(extra-files) add howto

- src/nixos-anywhere.sh
`ssh -t` is being used by `runSsh` which causes new lines in output designed for a terminal.  It could also output escape sequences.
https://unix.stackexchange.com/a/420438
this change fixes this problem (#438) by only outputting new lines.  but it might be worth removing ssh password entry as an option and the tty allocation, and force the use of sshpass for passwords.
There is a FIXME note regarding the output of the `nixos-facter` with _strange_ characters.  This may resolve that as well. 
Also updated the message about `nixos-facter` not being found to hopefully clarify and resolve #423 around the `--generate-hardware-config` option.
> fix(nixos-generate-config): dont output carriage returns in output files

- docs/quickstart.md
- src/nixos-anywhere.sh
- tests/flake-module.nix
- tests/from-nixos-separated-phases.nix
Will now use the provided `-i` (identity_file) as a stable deployment key - if specified - rather than always generating a random ephemeral SSH key.
This is primarily useful for the following reasons:
- error recovery
- controlled phases
*Error Recovery*
If `nixos-anywhere` stops with an error, we might want to connect remotely to the deployed machine. With the ephemeral key this might not be possible, because we don't necessarily have access to it anymore.
*Controlled Phases*
It is already possible to control which phases should be run. With an ephemeral key outside our control we are not able to resume the phases with a second `nixos-anywhere` invocation, because a different deployment key will now be generated.
> feat: Use `identity_file` as a deployment key

- docs/quickstart.md
`clan` is a deployment framework that also makes use of `nixos-anywhere`.
References:
- https://clan.lol/
- https://docs.clan.lol/getting-started/deploy
> docs: Add a reference to clan to quickstart

- src/nixos-anywhere.sh
Just a little debugging improvement
> --debug enables --show-trace on nix build commands

- src/nixos-anywhere.sh
Currently have no machine to test this on, but shellcheck seems happy.
Closes #464
> Fix --show-trace by using a bash array

- src/nixos-anywhere.sh
NixOS includes an option called `system.preSwitchChecks` since https://github.com/NixOS/nixpkgs/commit/6e192c4489ea44c48876faa11060798fb9502146.
As we are installing a new system here, we do not care too much about the systems state pre switching and therefore disable those checks. 
This change is motivated by https://github.com/nix-community/srvos/pull/591#issuecomment-2575221123
untested, but this might help @Kranzes?
> Don't run preSwitchChecks during install

- docs/cli.md
- src/nixos-anywhere.sh
This flag allows users to run nixos-anywhere with [extra settings for SSH store](https://nix.dev/manual/nix/2.22/store/types/ssh-store), by appending it to ssh store url.
If a user has fast connection between client and target, but slow internet connection on target, the user can use `--no-substitute-on-destination` to copy closures from client instead of downloading it from internet. 
The copy speed (nix-copy to ssh store) can be greatly improved by enabling compression via `--ssh-store-settings "compress=true"`.
Existing url parameters (especially the special characters) need to be encoded to avoid unexpected results. Otherwise we will get something like `root` evaluates to `/mnt?compression=true`.
> Add option --ssh-store-settings

- docs/howtos/extra-files.md
- docs/reference.md
- src/nixos-anywhere.sh
- tests/from-nixos.nix
I was in need to setting ownership for some extra files and will probably need it more going forward so I added a `--chown` option and documentation too.
> add option to set ownership of extraFiles

- src/nixos-anywhere.sh
This backs out commit be2d9d752660c95bb5232cd9829e150d05a90f25.
This backs out of #447
Now that https://github.com/nix-community/srvos/pull/591#issuecomment-2575221123 is fixed upstream, I think it would be preferable to run the pre-switch checks before installing to match the default behaviour of `nixos-install` and I usually think of `nixos-install` as `nixos-rebuild switch` with a few extra steps like installing a bootloader.
> Back out "Don't run preSwitchChecks during install"

- terraform/all-in-one/main.tf
- terraform/all-in-one/variables.tf
- terraform/nixos-rebuild/deploy.sh
- terraform/nixos-rebuild/main.tf
- terraform/nixos-rebuild/variables.tf
Without this, it isn't possible to for instance migrate from grub to systemd-boot, since there is no way to pass the flag to install the bootloader.
> feat: add a flag to reinstall the bootloader

- terraform/nixos-rebuild/deploy.sh
The previous commit added an argument but didn't increase the check on their number.
> fix arguments check in deploy.sh

- docs/requirements.md
- src/nixos-anywhere.sh
- tests/from-nixos-build-on-remote.nix
- tests/from-nixos-generate-config.nix
- tests/from-nixos-separated-phases.nix
- tests/from-nixos-with-sudo.nix
- tests/from-nixos.nix
if the user has a sudo password set, we were requiring multiple times to enter the sudo password. This now runs everything in one command to reduce the number of sudo invocation.
> runKexec: reduce number of ssh command needed for kexec

- src/nixos-anywhere.sh
otherwise it breaks because it contains multiple lines.
Fixes https://github.com/nix-community/nixos-anywhere/issues/528
> quote kexec command before running it.

- src/nixos-anywhere.sh
This PR significantly speeds up installing my system from scratch from around 1 hour down to 10 minutes with `--build-on remote` and substituting most of the paths from a HTTP binary cache.
The main speed up is from using `ssh-ng://` instead of `ssh://` for copying derivations by removing the `nix copy --derivation --to ssh://...` commands which is viable now that https://github.com/NixOS/nix/issues/7359 should be fixed.
SSH store compression makes a small but observable difference when copying derivations as part of the `nix build`.
> nixos-anywhere: speed up `--build-on remote`

- src/nixos-anywhere.sh
After kexec or if the remote host is already running a nixOS installer, we need to change the ssh user to root to proceed with the installation.
In the current implementation, we compute the ssh settings from the provided ssh connection string, extract the hostname option and rewrite the connection string as `root@hostname`.
There are two similar fields in an ssh config:
* hostname: the real ip/fqdn of the host
* host: the user configured alias for the host
For hosts with no configuration, host and hostname have the same value
```bash
ssh -G foo@some-unkown-server | grep -E '^(user|hostname|host|proxyjump)\s'
host some-unkown-server
user foo
hostname some-unkown-server
```
But if the host has an alias in the ssh config, the two fields can differ
```
Host server
HostName 1.2.3.4
ProxyJump …
```
> Preserve SSH options when switching to the root user

- src/nixos-anywhere.sh
This fixes an issue where the 2nd argument of
`--extra-experimental-features` is parsed as a flake, instead of the
argument to the flag
> Fix order of passing `nixOptions` in `nixos-facter call`

- src/nixos-anywhere.sh
This PR ensures that the backgrounded reboot command is fully detached, preventing SSH from occasionally hanging after the command is sent. By redirecting both stdout and stderr, the ssh session can close cleanly without waiting on open channels. This project is really cool and I hope to contribute a small improvement.
> Fully detach backgrounded reboot to prevent hanging SSH session

- src/nixos-anywhere.sh
This PR reverts #570 as I think we still want to run `nixos-facter` with `sudo` if possible and the changing the order of the flags doesn't fix the quoting issues
>  nixos-anywhere: fix running `nixos-facter` when it isn't installed

- src/get-facts.sh
- src/nixos-anywhere.sh
This PR can be more easily reviewed by going through each commit one at a time
> nixos-anywhere: reimport facts after kexec and throw if kexec failed

- src/nixos-anywhere.sh
- tests/from-nixos-build-on-remote.nix
- tests/from-nixos-generate-config.nix
- tests/from-nixos-separated-phases.nix
- tests/from-nixos-with-sudo.nix
- tests/from-nixos.nix
- tests/modules/installer.nix
support other compression than gzip
> kexec: support other compression than gzip
