nix-community/nixos-anywhere

bors.toml, flake.lock, flake.nix, src/nixos-remote.sh, tests/lib/test-base.nix, tests/modules/system-to-install.nix
This seems like a good idea to have, no strong opinions though.
=> treewide: add formatting via treefmt

src/nixos-remote.sh
This allows the user to monitor reboot happens from a script and run further actions after it comes back.
=> perform reboot in the background

src/default.nix
=> add missing dependencies 

src/nixos-remote.sh
=> detect nixos installer

src/nixos-remote.sh
=> use snake_case for variable names

.github/settings.yml
=> Update github settings w.r.t. repo name

.github/settings.yml
=> add pogobanane as contributor

src/default.nix, src/flake-module.nix
fixes https://github.com/numtide/nixos-anywhere/issues/62
=> prefer system's openssh

src/nixos-anywhere.sh
Cherry picked from https://github.com/numtide/nixos-anywhere/pull/50
=> Rsync permissions

src/nixos-anywhere.sh
`nixos-rebuild` does the same.
=> quote flake attr to allow dots in nixos hostname

terraform/nixos-rebuild/deploy.sh, terraform/nixos-rebuild/main.tf, terraform/nixos-rebuild/variables.tf
Add option to ignore systemd errors during deployment.
=> terraform/nixos-rebuild: do not ignore deploy errors by default

flake.lock, flake.nix, src/nixos-anywhere.sh, tests/from-nixos.nix, tests/modules/system-to-install.nix
since nixos-images upgraded: https://github.com/nix-community/nixos-images/pull/98
=> bash is no longer required

README.md
Flag was added in https://github.com/numtide/nixos-anywhere/pull/86
=> README.md: add build-on-remote

src/nixos-anywhere.sh
Let the user know what is happening by printing the high-level steps
in the console.
We could also be less verbose about the whole process at some point.
=> print the various steps

docs/quickstart.md
Populated the Quickstart guide
=> Added Quickstart guide

src/nixos-anywhere.sh
...to avoid a deprecation warning from disko
=> fix: .disko -> .diskoScript

README.md
https://github.com/numtide/nixos-anywhere/issues/126
=> README: remove deprecated partition type

src/nixos-anywhere.sh
I am currently experimenting with using nixos-install from normal linux distributions...
=> add workaround when running in non-nixos environments

bors.toml, flake.lock, flake.nix, src/nixos-anywhere.sh, tests/flake-module.nix
=> treewide: 22.11 -> 23.05

src/nixos-anywhere.sh
=> Add -t param to nixos-anywhere to enable for prompts during installation

src/nixos-anywhere.sh
squashed version of https://github.com/numtide/nixos-anywhere/pull/117
=> Add in ssh port option

README.md
power of two usually aligns better in the computer world
=> README: align boot partition to 512

flake.lock, src/default.nix
This is the format we have to use when upstreaming
=> package: align with nixpkgs version

README.md
https://github.com/nix-community/disko/blob/master/README.md?plain=1#L135
Matches the disko readme.
=> README: add missing line

docs/quickstart.md
error which has been introduced in #252
=> fix example url

docs/quickstart.md
Takes care of instances not handled by https://github.com/nix-community/nixos-anywhere/pull/253
=> Fix url for example repo

src/default.nix, src/get-facts.sh, src/nixos-anywhere.sh
[[ ]] is not available in POSIX sh, and test -o is not well defined either.
Move the facts-gathering script out so it can be tested with shellcheck.
=> fix bashism

src/nixos-anywhere.sh
=> Misc fixes to --extra-files

docs/cli.md, docs/quickstart.md, src/nixos-anywhere.sh
=> docs: correct SSHPASS variable and improve clarity

src/get-facts.sh, src/nixos-anywhere.sh
Instead of having flags like --no-reboot or --stop-after-disko, we now can specify all phases to run.
=> allow to disable/enable phases in nixos-anywhere

src/nixos-anywhere.sh
=> Fix sshKeyDir unbound variable

terraform/install/main.tf, terraform/install/run-nixos-anywhere.sh
=> terraform: fix SSH_PASS

docs/howtos/INDEX.md, docs/howtos/disko-modes.md, docs/quickstart.md, docs/reference.md, src/nixos-anywhere.sh
fix disko format mode
add howto to repair nixos installations
=> fix flags in nixos-generate-config examples

src/nixos-anywhere.sh
=> add swapoff to reboot phase

docs/quickstart.md
If the host only gives you a .pem file to SSH into the instance, you can still get your key and put it in there
=> Docs: specify how to obtain the key from a .pem file

flake.lock
=> bump nixos-images

docs/quickstart.md
I wasn't sure if I needed to prepend /dev/ and after trying it, it was necessary
=> docs: clarify what device path should be used

src/default.nix
Release 1.10.0 of nixpkgs-review
=> Release 1.10.0

src/default.nix
Release 1.11.0 of nixpkgs-review
=> Release 1.11.0
